[tool.poetry]
name = "dogcat"
version = "0.1.0"
description = ""
authors = ["Lillian Tsai"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
