[pytest]
markers =
    app-smoke: marker for smoke tests of the app
    case_id(id): Map the test case to a TestRail case ID.
    login: marker for tests that require login
    email_login: marker for tests that require email login
    line_login: marker for tests that require line login
    facebook_login: marker for tests that require Facebook login
bdd_features_base_dir = src/features/
junit_family = xunit2
addopts = --junitxml=results/results.xml --html=results/report.html